name: dhall-check
version: 1.0.0.1
synopsis: Check all dhall files in a project
description: 
github: anfelor/dhall-check
homepage: https://github.com/anfelor/dhall-check#readme
license: BSD3
license-file: LICENSE
author: Anton Felix Lorenzen
maintainer: anfelor@posteo.de
copyright: BSD3
category: Development

dependencies:
  - base >= 4.7 && < 5
  - containers 
  - directory
  - dhall
  - filepath
  - fsnotify
  - trifecta
  - text

executables:
  dhall-check:
    source-dirs:      src
    main:             Main.hs
